services:
  triton-server:
    image: nvcr.io/nvidia/tritonserver:22.12-py3
    container_name: triton_server
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    command: ["/opt/tritonserver/bin/tritonserver", "--model-repository=/models", "--log-verbose=1"]

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - triton-server
