name: "wav2vec_model"
platform: "onnxruntime_onnx"
max_batch_size: 4
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ 16000 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 49,768 ]
  }
]
